import {
  Baby,
  Bike,
  BookOpen,
  Camera,
  Car,
  Dumbbell,
  Gamepad2,
  GraduationCap,
  Home,
  MonitorPlay,
  Music,
  PartyPopper,
  Tent,
  Wrench,
  type LucideIcon,
} from "lucide-react";

export const categoryIcons: Record<string, LucideIcon> = {
  tools: Wrench,
  books: BookOpen,
  cameras: Camera,
  projectors: MonitorPlay,
  gaming: Gamepad2,
  camping: Tent,
  party: PartyPopper,
  sports: Bike,
  music: Music,
  fitness: Dumbbell,
  home: Home,
  kids: Baby,
  auto: Car,
  study: GraduationCap,
};
